pierstoval_character_generator_index:
    path: '/generate'
    defaults:
        _controller: Pierstoval\Bundle\CharacterManagerBundle\Controller\StepController:indexAction
        manager: null

pierstoval_character_generator_step:
    path: '/generate/{requestStep}'
    defaults:
        _controller: Pierstoval\Bundle\CharacterManagerBundle\Controller\StepController:stepAction
        manager: null
    requirements:
        requestStep: '[\w-]+'

pierstoval_character_generator_reset:
    path: '/reset/'
    defaults:
        _controller: Pierstoval\Bundle\CharacterManagerBundle\Controller\StepController:resetCharacterAction
        manager: null

pierstoval_character_generator_reset_step:
    path: '/reset/{requestStep}'
    defaults:
        _controller: Pierstoval\Bundle\CharacterManagerBundle\Controller\StepController:resetStepAction
        manager: null
    requirements:
        requestStep: '[\w-]+'
