pierstoval_character_generator_index:
    path: '/generate'
    defaults:
        _controller: 'pierstoval.character_manager.controller:indexAction'

pierstoval_character_generator_reset:
    path: '/reset/'
    defaults:
        _controller: 'pierstoval.character_manager.controller:resetAction'

pierstoval_character_generator_reset_step:
    path: '/reset/{requestStep}'
    defaults:
        _controller: 'pierstoval.character_manager.controller:resetStepAction'

pierstoval_character_generator_step:
    path: '/generate/{requestStep}'
    defaults:
        _controller: 'pierstoval.character_manager.controller:stepAction'
    requirements:
        'step': '[\w-]+'
