services:
    pierstoval.character_manager.actions_registry:
        class: Pierstoval\Bundle\CharacterManagerBundle\Registry\ActionsRegistry

    pierstoval.character_manager.step_action_resolver:
        class: Pierstoval\Bundle\CharacterManagerBundle\Resolver\StepActionResolver
        arguments:
            - '%pierstoval_character_manager.steps%'

    pierstoval.character_manager.controller:
        class: Pierstoval\Bundle\CharacterManagerBundle\Controller\StepController
        arguments:
            - '%pierstoval_character_manager.character_class%'
            - '@pierstoval.character_manager.step_action_resolver'
            - '@templating.engine.twig'
            - '@translator'
            - '@doctrine.orm.entity_manager'
            - '@router.default'
            - '@pierstoval.character_manager.actions_registry'
