services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pierstoval\Bundle\CharacterManagerBundle\Registry\ActionsRegistry: ~
    Pierstoval\Bundle\CharacterManagerBundle\Registry\ActionsRegistryInterface: '@Pierstoval\Bundle\CharacterManagerBundle\Registry\ActionsRegistry'

    Pierstoval\Bundle\CharacterManagerBundle\Resolver\StepResolver: ~
    Pierstoval\Bundle\CharacterManagerBundle\Resolver\StepResolverInterface: '@Pierstoval\Bundle\CharacterManagerBundle\Resolver\StepResolver'

    Pierstoval\Bundle\CharacterManagerBundle\Controller\StepController:
        public: true
