language: php

php:
    - 7.1

env:
    - SYMFONY_VERSION="3.0.*"
    - SYMFONY_VERSION="3.3.*"
    - SYMFONY_VERSION="3.4@beta"
    - SYMFONY_VERSION="4.0@beta"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.app/cache

before_install:
    - composer selfupdate
    - composer install --no-interaction
    - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar; fi
    - cat phpunit.xml.dist | sed -e 's/\(<!--\)\|\(-->\)//g' > phpunit.xml

script:
    - vendor/bin/phpunit

after_success: |
    if [[ "$TRAVIS_PHP_VERSION" == "7.1" && "$SYMFONY_VERSION" == "3.3.*" ]]; then php coveralls.phar -v --config .coveralls.yml; fi;

notifications:
    email: pierstoval@gmail.com
