# This .travis.yml file is just a copy of EasyAdminBundle's one
# Check it out there: https://github.com/javiereguiluz/EasyAdminBundle
# We just rise the lowest PHP version to 5.5 because we use Symfony 3.

language: php

php:
    - 5.6
    - 7.0

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.app/cache

before_install:
  - composer selfupdate
  - composer install --no-interaction
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then composer require --dev satooshi/php-coveralls; fi

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success: |
    if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then php vendor/bin/coveralls -v --config .coveralls.yml; fi;

notifications:
  email: pierstoval@gmail.com
