language: php

sudo: false

cache:
    directories:
      - $HOME/.composer/cache
      - $HOME/.app/cache

php: 7.1

env:
  global:
    - COMPOSER_FLAGS=""
    - TWIG_VERSION=""
    - SYMFONY_VERSION=""
    - ENABLE_CODE_COVERAGE="false"

matrix:
    fast_finish: true
    include:
        - env: 'COMPOSER_FLAGS="--prefer-lowest"'
        - env: 'SYMFONY_VERSION="3.4.*"'
        - env: 'SYMFONY_VERSION="4.0.*"'
        - env: 'ENABLE_CODE_COVERAGE="true"'

before_install:
    - 'if [[ "$SYMFONY_VERSION" != "" ]]; then sed -r -e "s/(symfony\/[^:]+: \").+(\",?)$/\1$SYMFONY_VERSION\2/" -i composer.json; fi;'
    - 'if [[ "$SYMFONY_VERSION" == *beta ]]; then composer config minimum-stability beta; fi;'
    - 'if [[ "$ENABLE_CODE_COVERAGE" != "true" ]]; then phpenv config-rm xdebug.ini; fi;'
    - 'cat phpunit.xml.dist | sed -e "s/\(<!--\)\|\(-->\)//g" > phpunit.xml'
    - 'if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar; fi;'

install:
    - composer update --prefer-dist --no-interaction --optimize-autoloader $COMPOSER_FLAGS
    - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then composer require --dev satooshi/php-coveralls; fi

script:
    - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml; else phpunit; fi;

after_success: |
    if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then php vendor/bin/coveralls -v --config .coveralls.yml; fi;

notifications:
    email: pierstoval@gmail.com
