language: php

sudo: false

cache:
    directories:
      - $HOME/.composer/cache
      - $HOME/.app/cache

php: 7.2

matrix:
    fast_finish: true
    include:
        - env: 'ENABLE_CODE_COVERAGE="false"'
        - env: 'ENABLE_CODE_COVERAGE="true"'

before_install:
    - 'if [[ "$SYMFONY_VERSION" != "" ]]; then sed -r -e "s/(symfony\/[^:]+: \").+(\",?)$/\1$SYMFONY_VERSION\2/" -i composer.json; fi;'
    - 'if [[ "$ENABLE_CODE_COVERAGE" != "true" ]]; then phpenv config-rm xdebug.ini; fi;'
    - 'if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar; fi;'

install:
    - composer update --prefer-dist --no-interaction --optimize-autoloader

script:
    - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi;

after_success: |
    if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then php php-coveralls.phar -v --config .coveralls.yml; fi;
