# This .travis.yml file is just a copy of EasyAdminBundle's one
# Check it out there: https://github.com/javiereguiluz/EasyAdminBundle
# We just rise the lowest PHP version to 5.5 because we use Symfony 3.

language: php

php:
    - 5.6
    - 7.0
    - 7.1

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.app/cache

before_install:
  - composer selfupdate
  - composer install --no-interaction
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar; fi

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success: |
    if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php coveralls.phar -v --config .coveralls.yml; fi;

notifications:
  email: pierstoval@gmail.com
