name: PHP CI

on: [push]

jobs:
    build-test:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                operating-system:
                    - ubuntu-latest
                    - macOS-latest
                    - windows-latest
                php-version:
                    - '8.0'
                    - '8.1'

        name: PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "${{ matrix.php-version }}"

            - name: Composer install
              uses: "ramsey/composer-install@v1"

            - name: Install PHPUnit
              run: |
                export "SYMFONY_DEPRECATIONS_HELPER=max[self]=0"
                vendor/bin/simple-phpunit --version

            - name: 🚀 Run PHPUnit tests
              run: vendor/bin/simple-phpunit
